import numpy as np
uninitialised_array = np.empty(shape=(2, 3))
print("Uninitialised Array:")
print(uninitialised_array)
array_one = np.ones(shape=(2, 3))
print("Array with ones:")
print(array_one)
array_zero = np.zeros(shape=(2, 3))
print("Array with zeros:")
print(array_zero)
